// extracted from WZANIM_INJECT (was a runtime monkey-patch)
/*WZANIM_INJECT*/
(function(){
 if(window.__wzAnim)return; window.__wzAnim=1;
 var IDS=['w1','w2','w3','w4','w5','w6'],W=['warrior-boy.png','warrior-2.png','warrior-3.png','warrior-girl.png','warrior-5.png','warrior-6.png'];
 function curImg(){try{var a=(window.APP&&APP.kid&&APP.kid.avatar)||'';var i=IDS.indexOf(a);return 'img/'+(i>=0?W[i]:'warrior-boy.png');}catch(e){return 'img/warrior-boy.png';}}
 function style(){ if(document.getElementById('wz-anim-css'))return; var s=document.createElement('style'); s.id='wz-anim-css'; s.textContent="@keyframes wzfloat{0%,100%{transform:translateY(0) rotate(-1.2deg)}50%{transform:translateY(-14px) rotate(1.2deg)}} @keyframes wzpulse{0%,100%{opacity:.30;transform:scale(1)}50%{opacity:.6;transform:scale(1.09)}} @keyframes wzspark{0%{transform:translateY(30px) scale(.5);opacity:0}25%{opacity:1}100%{transform:translateY(-190px) scale(1.05);opacity:0}} @keyframes wzfloatB{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}} .wz-armor-stage{position:relative;height:320px;display:flex;align-items:center;justify-content:center;overflow:hidden;border-radius:16px} .wz-armor-hero{height:90%;filter:drop-shadow(0 12px 22px rgba(0,0,0,.55));animation:wzfloat 3.6s ease-in-out infinite;z-index:2;-webkit-mask-image:radial-gradient(ellipse 60% 74% at 50% 44%, #000 60%, rgba(0,0,0,0) 90%);mask-image:radial-gradient(ellipse 60% 74% at 50% 44%, #000 60%, rgba(0,0,0,0) 90%)} .wz-aura{position:absolute;width:360px;height:360px;border-radius:50%;background:radial-gradient(circle,rgba(245,200,66,.55),rgba(245,200,66,0) 68%);animation:wzpulse 3.8s ease-in-out infinite;z-index:1} .wz-ring{position:absolute;bottom:34px;width:200px;height:44px;border-radius:50%;background:radial-gradient(ellipse,rgba(245,200,66,.5),rgba(245,200,66,0) 70%);z-index:1;filter:blur(2px)} .wz-spark{position:absolute;bottom:60px;width:9px;height:9px;border-radius:50%;background:#ffe89a;box-shadow:0 0 10px #f5c842;animation:wzspark linear infinite;z-index:3} .wz-fullbadge{position:absolute;top:14px;left:50%;transform:translateX(-50%);background:#f5c842;color:#1a1a2e;font-family:Bangers,cursive;letter-spacing:.05em;padding:5px 18px;border-radius:14px;font-size:20px;z-index:4;box-shadow:0 4px 14px rgba(0,0,0,.45)} #wz-hero-banner>div:nth-child(3){animation:wzfloatB 4.2s ease-in-out infinite}"; document.head.appendChild(s); }
 function sparkles(){var h='';for(var i=0;i<9;i++){var l=(8+Math.random()*84).toFixed(0);var d=(Math.random()*3).toFixed(2);var dur=(2.6+Math.random()*2).toFixed(2);h+="<div class='wz-spark' style='left:"+l+"%;animation-delay:"+d+"s;animation-duration:"+dur+"s'></div>";}return h;}
 function repoint(){var b=[].slice.call(document.querySelectorAll('#tab-warrior button')).find(function(x){return /customize/i.test(x.textContent);}); if(b&&window.wzOpenWarriorPicker){b.onclick=function(e){if(e)e.preventDefault();window.wzOpenWarriorPicker();};}}
 function enhanceArmor(){var tw=document.getElementById('tab-warrior');if(!tw)return;var svg=tw.querySelector('svg');var box=svg?svg.parentElement:tw.querySelector('[data-wzstage]');if(!box)return;var life=(window.APP&&APP.kid&&APP.kid.lifetime_points)||0;var th=[25,100,250,500,800,1200];var earned=th.filter(function(x){return life>=x;}).length;var auraOp=(0.22+earned*0.06).toFixed(2);var auraSc=(0.72+earned*0.05).toFixed(2);box.setAttribute('data-wzstage','1');box.innerHTML="<div class='wz-armor-stage'><div class='wz-aura' style='opacity:"+auraOp+";transform:scale("+auraSc+")'></div><div class='wz-ring'></div>"+sparkles()+"<img class='wz-armor-hero' src='"+curImg()+"'>"+(earned>=6?"<div class='wz-fullbadge'>FULL ARMOR!</div>":"")+"</div>";repoint();}
 function hookRender(){ if(typeof window.renderArmor==='function'&&!window.renderArmor.__wza){var orig=window.renderArmor;window.renderArmor=function(){var r=orig.apply(this,arguments);try{enhanceArmor();}catch(e){}return r;};window.renderArmor.__wza=1;} }
 function hookTab(){ if(typeof window.dashTab==='function'&&!window.dashTab.__wzaTab){var orig=window.dashTab;window.dashTab=function(tab,btn){var r=orig.apply(this,arguments);try{if(tab==='warrior')setTimeout(enhanceArmor,30);}catch(e){}return r;};window.dashTab.__wzaTab=1;} }
 function init(){style();hookRender();hookTab();try{enhanceArmor();}catch(e){}}
 setTimeout(init,200);setTimeout(init,900);setTimeout(init,2000);
})();
