// extracted from WZCELE_INJECT (was a runtime monkey-patch)
/*WZCELE_INJECT*/
(function(){
 if(window.__wzCele)return; window.__wzCele=1;
 var P=[{n:"Belt of Truth",e:"🎗️",v:"Stand therefore, having fastened on the belt of truth",r:"Ephesians 6:14 (ESV)"},{n:"Breastplate of Righteousness",e:"🦺",v:"having put on the breastplate of righteousness",r:"Ephesians 6:14 (ESV)"},{n:"Gospel Boots",e:"👟",v:"as shoes for your feet, having put on the readiness given by the gospel of peace",r:"Ephesians 6:15 (ESV)"},{n:"Shield of Faith",e:"🛡️",v:"take up the shield of faith, with which you can extinguish all the flaming darts of the evil one",r:"Ephesians 6:16 (ESV)"},{n:"Helmet of Salvation",e:"⛑️",v:"take the helmet of salvation",r:"Ephesians 6:17 (ESV)"},{n:"Sword of the Spirit",e:"⚔️",v:"the sword of the Spirit, which is the word of God",r:"Ephesians 6:17 (ESV)"},{n:"The Full Armor of God",e:"✨",v:"Put on the whole armor of God, that you may be able to stand against the schemes of the devil",r:"Ephesians 6:11 (ESV)"}];
 function celCss(){if(document.getElementById('wz-cel-css'))return;var s=document.createElement('style');s.id='wz-cel-css';s.textContent="#wz-cel{position:fixed;inset:0;z-index:2147483600;display:flex;align-items:center;justify-content:center;padding:18px;background:radial-gradient(circle at 50% 40%,rgba(40,18,90,.86),rgba(6,3,20,.94));overflow:hidden;animation:wzcelin .3s ease} @keyframes wzcelin{from{opacity:0}to{opacity:1}} #wz-cel .rays{position:absolute;top:42%;left:50%;width:900px;height:900px;transform:translate(-50%,-50%);background:repeating-conic-gradient(from 0deg,rgba(245,200,66,.14) 0deg 6deg,rgba(245,200,66,0) 6deg 20deg);-webkit-mask:radial-gradient(circle,#000 10%,rgba(0,0,0,0) 60%);mask:radial-gradient(circle,#000 10%,rgba(0,0,0,0) 60%);animation:wzcelrays 30s linear infinite} @keyframes wzcelrays{to{transform:translate(-50%,-50%) rotate(360deg)}} #wz-cel .card{position:relative;z-index:2;max-width:420px;width:100%;text-align:center;background:linear-gradient(160deg,#1b0b49,#2c1170);border:2px solid rgba(245,200,66,.6);border-radius:26px;padding:24px 22px 20px;box-shadow:0 20px 60px rgba(0,0,0,.6);animation:wzcelpop .5s cubic-bezier(.2,1.3,.4,1)} @keyframes wzcelpop{from{transform:translateY(24px) scale(.9);opacity:0}to{transform:none;opacity:1}} #wz-cel .eyebrow{color:#f5c842;font-weight:800;letter-spacing:.14em;font-size:12px} #wz-cel .badge{width:104px;height:104px;margin:12px auto 6px;border-radius:50%;background:radial-gradient(circle,#f7d873,#e0a92b);display:flex;align-items:center;justify-content:center;font-size:52px;box-shadow:0 0 0 8px rgba(245,200,66,.22),0 8px 22px rgba(0,0,0,.45);animation:wzbadge 2.4s ease-in-out infinite} @keyframes wzbadge{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-6px) scale(1.05)}} #wz-cel .pname{font-family:Bangers,cursive;color:#fff;font-size:30px;letter-spacing:.03em;margin:4px 0 2px;text-shadow:0 2px 8px rgba(0,0,0,.5)} #wz-cel .verse{color:#e7e3f5;font-size:14px;font-style:italic;line-height:1.4;margin:8px 6px 4px} #wz-cel .ref{color:#f5c842;font-weight:700;font-size:12px;margin-bottom:14px} #wz-cel .go{background:#f5c842;color:#1a1a2e;font-weight:800;border:none;border-radius:16px;padding:11px 22px;font-size:15px;cursor:pointer;font-family:Bangers,cursive;letter-spacing:.04em} .wz-conf{position:fixed;top:-16px;width:11px;height:15px;z-index:2147483590;opacity:.95;animation:wzconf linear forwards} @keyframes wzconf{to{transform:translateY(105vh) rotate(720deg);opacity:.9}}";document.head.appendChild(s);}
 function confettiBurst(n){var C=['#f5c842','#ffd76b','#7b5cff','#ff6b9d','#4fd1c5','#ffffff'];for(var i=0;i<n;i++){var d=document.createElement('div');d.className='wz-conf';d.style.left=(Math.random()*100)+'vw';d.style.background=C[i%C.length];d.style.animationDuration=(2.2+Math.random()*1.8)+'s';d.style.animationDelay=(Math.random()*.5)+'s';d.style.transform='rotate('+(Math.random()*360)+'deg)';if(Math.random()<.5)d.style.borderRadius='50%';document.body.appendChild(d);setTimeout(function(el){el.remove();},4200,d);}}
 function install(){ celCss(); window.wzArmorCelebrate=function(id){ celCss(); var life=(window.APP&&APP.kid&&APP.kid.lifetime_points)||0;var th=[25,100,250,500,800,1200,1800];var earned=th.filter(function(x){return life>=x;}).length; var idx=(typeof id==='number'&&id>=0&&id<7)?id:Math.max(0,earned-1); var p=P[idx]||P[0]; var ex=document.getElementById('wz-cel');if(ex)ex.remove(); var ov=document.createElement('div');ov.id='wz-cel'; ov.innerHTML="<div class='rays'></div><div class='card'><div class='eyebrow'>NEW ARMOR UNLOCKED!</div><div class='badge'>"+p.e+"</div><div class='pname'>"+p.n+"</div><div class='verse'>“"+p.v+"”</div><div class='ref'>"+p.r+"</div><button class='go'>Keep Going, Warrior!</button></div>"; document.body.appendChild(ov); confettiBurst(70); try{if(window.wzConfetti)wzConfetti(40);}catch(e){} try{if(window.wzSfxFanfare && localStorage.getItem('wz_mute')!=='1')wzSfxFanfare();}catch(e){} function close(){var o=document.getElementById('wz-cel');if(o)o.remove();} ov.querySelector('.go').onclick=close; ov.addEventListener('click',function(e){if(e.target===ov)close();}); }; }
 setTimeout(install,300);setTimeout(install,1200);setTimeout(install,2600);
})();
