// extracted from WZHERO2_INJECT (was a runtime monkey-patch)
/*WZHERO2_INJECT*/
(function(){
 if(window.__wzHero2)return; window.__wzHero2=1;
 var W=['warrior-boy.png','warrior-2.png','warrior-3.png','warrior-girl.png','warrior-5.png','warrior-6.png'];
 var IDS=['w1','w2','w3','w4','w5','w6'];
 function idImg(id){var i=IDS.indexOf(id);return 'img/'+(i>=0?W[i]:'warrior-boy.png');}
 function curImg(){try{return idImg((window.APP&&APP.kid&&APP.kid.avatar)||'');}catch(e){return 'img/warrior-boy.png';}}
 function chosen(){try{return IDS.indexOf((window.APP&&APP.kid&&APP.kid.avatar)||'')>=0;}catch(e){return false;}}
 var SCN={watch:'bg-watch.jpg',verse:'bg-verse.jpg',games:'bg-games.jpg',training:'bg-games.jpg',jesus:'bg-verse.jpg',devos:'bg-verse.jpg',prayer:'bg-verse.jpg'};
 function scnFor(t){return SCN[t]||'bg-watch.jpg';}
 function style(){ if(document.getElementById('wz-hero2-css'))return; var s=document.createElement('style'); s.id='wz-hero2-css'; s.textContent="#p-dash::before{background-image:none !important} #dash-hero::after{display:none !important} #wz-hero-banner{animation:wzhin .4s ease} @keyframes wzhin{from{opacity:0;transform:translateY(-6px)}to{opacity:1;transform:none}} #wz-change-warrior{cursor:pointer;background:rgba(255,255,255,.14);color:#fff;border:1px solid rgba(255,255,255,.3);border-radius:14px;padding:5px 12px;font-size:12px;font-weight:700} #wz-change-warrior:hover{background:rgba(255,255,255,.24)} #wz-pick-ov{position:fixed;inset:0;z-index:2147483000;background:rgba(6,3,20,.93);display:flex;flex-direction:column;align-items:center;overflow:auto;padding:24px 14px} .wz-pick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;max-width:680px;width:100%} @media(max-width:560px){.wz-pick-grid{grid-template-columns:repeat(2,1fr)}} .wz-pick-card{position:relative;border-radius:18px;overflow:hidden;cursor:pointer;background:linear-gradient(160deg,#1a0b47,#2c1170);border:3px solid transparent;aspect-ratio:3/4} .wz-pick-card img{width:100%;height:100%;object-fit:cover;display:block} .wz-pick-card:hover{transform:translateY(-3px)} .wz-pick-card.sel{border-color:#f5c842;box-shadow:0 0 0 4px rgba(245,200,66,.35)}"; document.head.appendChild(s); }
 function banner(tab){ var dm=document.getElementById('dash-main'); if(!dm)return; var k=(window.APP&&APP.kid)||{}; var name=k.first_name||'Warrior'; var pts=(k.points!=null?k.points:0); var old=document.getElementById('wz-hero-banner'); if(old)old.remove(); var b=document.createElement('div'); b.id='wz-hero-banner'; b.style.cssText='position:relative;overflow:hidden;border-radius:22px;margin:0 0 16px;min-height:172px;box-shadow:0 10px 26px rgba(0,0,0,.45);background:#160a3e'; b.innerHTML="<div style='position:absolute;inset:0;background:url(img/"+scnFor(tab)+") center/cover'></div><div style='position:absolute;inset:0;background:linear-gradient(90deg,rgba(10,6,30,.94) 0%,rgba(10,6,30,.72) 42%,rgba(10,6,30,.22) 66%,rgba(10,6,30,0) 100%)'></div><div style='position:absolute;right:-1%;bottom:-8%;top:-4%;width:40%;background:url("+curImg()+") right bottom/contain no-repeat;filter:drop-shadow(0 6px 14px rgba(0,0,0,.5))'></div><div style='position:relative;z-index:2;padding:20px 40% 20px 24px'><div style='color:#f5c842;font-weight:800;font-size:12px;letter-spacing:.12em'>WELCOME BACK</div><div style='color:#fff;font-family:Bangers,cursive;font-size:36px;line-height:1.05;margin:2px 0 6px;text-shadow:0 2px 8px rgba(0,0,0,.5)'>Hey, "+name+"!</div><div style='color:#e7e3f5;font-size:14px;text-shadow:0 1px 4px rgba(0,0,0,.6)'>You are a mighty warrior of God. Put on the full armor and keep going!</div><div style='margin-top:12px;display:flex;gap:10px;align-items:center'><span style='background:#f5c842;color:#1a1a2e;font-weight:800;padding:6px 14px;border-radius:16px;font-size:14px'>&#11088; "+pts+" points</span><button id='wz-change-warrior'>Change Warrior</button></div></div>"; dm.insertBefore(b,dm.firstChild); var cb=document.getElementById('wz-change-warrior'); if(cb)cb.onclick=function(){openPicker();}; }
 function openPicker(){ if(document.getElementById('wz-pick-ov'))return; var k=(window.APP&&APP.kid)||{}; var cur=k.avatar||''; var ov=document.createElement('div'); ov.id='wz-pick-ov'; var cards=IDS.map(function(id,i){return "<div class='wz-pick-card"+(id===cur?' sel':'')+"' data-id='"+id+"'><img src='img/"+W[i]+"'></div>";}).join(''); ov.innerHTML="<div style='color:#fff;font-family:Bangers,cursive;font-size:34px;margin:6px 0 2px'>Choose Your Warrior!</div><div style='color:#cfc9e8;font-size:14px;margin-bottom:16px'>Tap the hero you want to be.</div><div class='wz-pick-grid'>"+cards+"</div><button id='wz-pick-close' style='margin:18px 0;background:#f5c842;color:#1a1a2e;font-weight:800;border:none;border-radius:16px;padding:10px 22px;font-size:15px;cursor:pointer'>Done</button>"; document.body.appendChild(ov); ov.querySelectorAll('.wz-pick-card').forEach(function(c){c.onclick=function(){choose(c.getAttribute('data-id'),ov);};}); document.getElementById('wz-pick-close').onclick=function(){ov.remove();}; }
 function choose(id,ov){ var k=(window.APP&&APP.kid)||{}; ov.querySelectorAll('.wz-pick-card').forEach(function(c){c.classList.toggle('sel',c.getAttribute('data-id')===id);}); fetch('https://ktuapfiexhlladgkuauc.supabase.co/functions/v1/wz-avatar',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({kid_id:k.id,pin:k.pin,choice:id})}).then(function(r){return r.json();}).then(function(res){ if(res&&res.ok){ if(window.APP&&APP.kid)APP.kid.avatar=id; banner(curTab()); setTimeout(function(){var o=document.getElementById('wz-pick-ov');if(o)o.remove();},350);} }).catch(function(){}); }
 function curTab(){var b=document.querySelector('.tab-sidebar-btn.active,.tab-btn.active'); if(!b)return 'watch'; var t=(b.textContent||'').toLowerCase(); var ks=['watch','verse','games','training','jesus','devos','prayer']; for(var i=0;i<ks.length;i++){if(t.indexOf(ks[i])>=0)return ks[i];} return 'watch';}
 function maybePrompt(){try{ if(!window.__wzPickPrompted && (window.APP&&APP.kid) && !chosen()){ window.__wzPickPrompted=1; setTimeout(openPicker,900); } }catch(e){}}
 function hook(){ style(); if(typeof window.dashTab==='function'&&!window.dashTab.__wzh2){ var orig=window.dashTab; window.dashTab=function(tab,btn){var r=orig.apply(this,arguments);try{banner(tab);maybePrompt();}catch(e){}return r;}; window.dashTab.__wzh2=1; } try{banner(curTab());}catch(e){} maybePrompt(); window.wzOpenWarriorPicker=openPicker; }
 setTimeout(hook,160);setTimeout(hook,800);setTimeout(hook,1800);setTimeout(maybePrompt,2600);
})();
