[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/kids"
  to = "https://kids.gatheringctx.org"
  status = 301
  force = true

[[redirects]]
  from = "/kids/*"
  to = "https://kids.gatheringctx.org/:splat"
  status = 301
  force = true
